#theme: minima

# новая версия в разработке выставил коммит на стабильную 2.5 версию (можно убрать @коммит)
remote_theme: jekyll/minima@593a05a

title: Sports scoreboard for streaming on Mac
description: Broadcasts with statistics via OBS, WireCast, Streamlabs, etc.

plugins:
  - jekyll-feed

minima:
  skin: auto

header_pages:
  - guides.md
  - PRIVACY_POLICY.md
  - support.md
