# Это если использовать настройки gem и брать из гема
#theme: minima

# новая версия в разработке выставил коммит на стабильную 2.5 версию (можно убрать @коммит)
#remote_theme: jekyll/minima@1e8a445
remote_theme: jekyll/minima

title: ScoreBoard for Mac
description: >
  Sports scoreboard app for streaming on Mac: live score, timer and stats overlays
  for OBS, Streamlabs, Wirecast and Meld.
#author:
#  name: Vasily Petukhov

minima:
  skin: auto
  hide_site_feed_link: true
  nav_pages:
    - guides.md
    - PRIVACY_POLICY.md
    - support.md

#header_pages:
#  - guides.md
#  - PRIVACY_POLICY.md
#  - support.md

plugins:
  - jekyll-sitemap
#  - jekyll-feed
